parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true


    App\:
        resource: '../src/'

    App\Handler\:
        resource: '../src/Handler/'
        tags: ['app.message_handler']

    App\Registry\MessageHandlerRegistry:
        arguments:
            $handlers: !tagged_iterator app.message_handler


